sudo: required
services:
  - docker

before_install:
  - docker build -t timclifford/docker-react-travis -f Dockerfile.dev .

script:
  - docker run timclifford/docker-react-travis npm run test -- --coverage
